// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProximityService.Data;

#nullable disable

namespace ProximityService.Migrations
{
    [DbContext(typeof(ProximityDbContext))]
    [Migration("20260608201308_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProximityService.Data.BusinessLocation", b =>
                {
                    b.Property<string>("BusinessId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Geohash")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("BusinessId");

                    b.HasIndex("Geohash")
                        .HasDatabaseName("IX_Business_Geohash");

                    b.HasIndex("Geohash", "Category")
                        .HasDatabaseName("IX_BusinessLocation_Geohash_Category");

                    b.ToTable("Businesses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
